// apps/dashboard/src/lib/components/ProfileDesigner.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import Chart, { type ECOption } from '$lib/components/Chart.svelte';
	import { profiles, type CreateProfileRequest, type ProfileWithPoints } from '$lib/api/client.js';
	import { notifications } from '$lib/stores/notifications.js';
	import { Trash2, Table, LineChart } from 'lucide-svelte';

	interface DesignerPoint {
		time_seconds: number;
		target_temp: number;
		fan_speed: number | null;
	}

	let {
		initialProfile = null
	}: {
		initialProfile?: ProfileWithPoints | null;
	} = $props();

	// Extract initial values once (intentionally non-reactive)
	const initName = initialProfile?.name ?? '';
	const initDescription = initialProfile?.description ?? '';
	const initChargeTemp = initialProfile?.charge_temp ?? undefined;
	const initTargetEndTemp = initialProfile?.target_end_temp ?? undefined;
	const initPoints: DesignerPoint[] = initialProfile?.points
		? [...initialProfile.points]
				.sort((a, b) => a.time_seconds - b.time_seconds)
				.map((p) => ({
					time_seconds: p.time_seconds,
					target_temp: p.target_temp,
					fan_speed: p.fan_speed
				}))
		: [];
	const profileId = initialProfile?.id ?? null;

	// Metadata state
	let name = $state(initName);
	let description = $state(initDescription);
	let chargeTemp = $state<number | undefined>(initChargeTemp);
	let targetEndTemp = $state<number | undefined>(initTargetEndTemp);

	// Points state
	let points = $state<DesignerPoint[]>(initPoints);
	let selectedIndex = $state<number | null>(null);
	let viewMode = $state<'chart' | 'table'>('chart');
	let saving = $state(false);

	let chartComponent: ReturnType<typeof Chart> | undefined = $state();

	// Sort points helper
	function sortedPoints(): DesignerPoint[] {
		return [...points].sort((a, b) => a.time_seconds - b.time_seconds);
	}

	// Add point
	function addPoint(timeSec: number, temp: number) {
		const newPoint: DesignerPoint = {
			time_seconds: Math.round(timeSec),
			target_temp: Math.round(temp * 10) / 10,
			fan_speed: null
		};
		points.push(newPoint);
		points.sort((a, b) => a.time_seconds - b.time_seconds);
		selectedIndex = points.indexOf(newPoint);
	}

	// Delete selected point
	function deleteSelected() {
		if (selectedIndex === null || selectedIndex < 0 || selectedIndex >= points.length) return;
		points.splice(selectedIndex, 1);
		selectedIndex = null;
	}

	// Handle keyboard delete
	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Delete' && selectedIndex !== null) {
			deleteSelected();
		}
	}

	// Chart click handler setup
	let chartHandlersAttached = false;

	$effect(() => {
		if (!chartComponent || chartHandlersAttached) return;
		const instance = chartComponent.getInstance();
		if (!instance) return;

		// Click on blank area to add point
		instance.getZr().on('click', (params: { target?: unknown; offsetX: number; offsetY: number }) => {
			if (params.target) return; // clicked on a series element
			const dataPoint = instance.convertFromPixel('grid', [params.offsetX, params.offsetY]);
			if (dataPoint) {
				const [timeSec, temp] = dataPoint;
				if (timeSec >= 0 && temp >= 0 && temp <= 350) {
					addPoint(timeSec, temp);
				}
			}
		});

		// Click on existing point to select
		instance.on('click', (params: { dataIndex?: number; componentType?: string; seriesName?: string }) => {
			if (params.componentType === 'series' && params.seriesName === 'Profile' && params.dataIndex !== undefined) {
				// Find the matching point in our sorted array
				const sorted = sortedPoints();
				if (params.dataIndex < sorted.length) {
					const clickedPoint = sorted[params.dataIndex];
					const idx = points.findIndex(
						(p) => p.time_seconds === clickedPoint.time_seconds && p.target_temp === clickedPoint.target_temp
					);
					selectedIndex = idx >= 0 ? idx : null;
				}
			}
		});

		chartHandlersAttached = true;
	});

	// Chart options
	let chartOption = $derived.by<ECOption>(() => {
		const sorted = sortedPoints();
		const chartData = sorted.map((p) => [p.time_seconds, p.target_temp]);

		// Highlight selected point
		let selectedData: number[][] = [];
		if (selectedIndex !== null && selectedIndex >= 0 && selectedIndex < points.length) {
			const p = points[selectedIndex];
			selectedData = [[p.time_seconds, p.target_temp]];
		}

		return {
			animation: false,
			grid: { left: 55, right: 20, top: 30, bottom: 45 },
			tooltip: {
				trigger: 'item',
				formatter: (params: unknown) => {
					const p = params as { data?: number[] };
					if (!p.data) return '';
					const [t, temp] = p.data;
					const m = Math.floor(t / 60);
					const s = Math.round(t % 60);
					return `Time: ${m}:${s.toString().padStart(2, '0')}<br/>Temp: ${temp}°C`;
				}
			},
			xAxis: {
				type: 'value',
				name: 'Time (s)',
				min: 0,
				nameTextStyle: { color: '#9ca3af' },
				axisLabel: {
					color: '#9ca3af',
					formatter: (val: number) => {
						const m = Math.floor(val / 60);
						const s = Math.round(val % 60);
						return `${m}:${s.toString().padStart(2, '0')}`;
					}
				},
				axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
				splitLine: { show: false }
			},
			yAxis: {
				type: 'value',
				name: 'Temp (°C)',
				min: 0,
				nameTextStyle: { color: '#9ca3af' },
				axisLabel: { color: '#9ca3af' },
				axisLine: { lineStyle: { color: 'rgba(255,255,255,0.1)' } },
				splitLine: { lineStyle: { color: 'rgba(255,255,255,0.06)' } }
			},
			series: [
				{
					name: 'Profile',
					type: 'line',
					data: chartData,
					itemStyle: { color: '#f59e0b' },
					lineStyle: { width: 2 },
					showSymbol: true,
					symbolSize: 10,
					emphasis: {
						itemStyle: { borderWidth: 3, borderColor: '#fff' }
					}
				},
				...(selectedData.length > 0
					? [
							{
								name: 'Selected',
								type: 'line' as const,
								data: selectedData,
								itemStyle: { color: '#ef4444', borderWidth: 2 },
								symbolSize: 14,
								showSymbol: true,
								lineStyle: { width: 0 }
							}
						]
					: [])
			]
		};
	});

	// Save handler
	async function handleSave() {
		if (!name.trim()) {
			notifications.add('Profile name is required', 'error');
			return;
		}
		if (points.length === 0) {
			notifications.add('At least one point is required', 'error');
			return;
		}

		saving = true;
		try {
			const sorted = sortedPoints();
			const totalTime = sorted.length > 0 ? sorted[sorted.length - 1].time_seconds : undefined;
			const req: CreateProfileRequest = {
				name: name.trim(),
				description: description.trim() || undefined,
				charge_temp: chargeTemp,
				target_end_temp: targetEndTemp,
				target_total_time: totalTime,
				points: sorted.map((p) => ({
					time_seconds: p.time_seconds,
					target_temp: p.target_temp,
					fan_speed: p.fan_speed ?? undefined
				}))
			};

			if (profileId) {
				await profiles.update(profileId, req);
				notifications.add('Profile updated', 'success');
			} else {
				await profiles.create(req);
				notifications.add('Profile created', 'success');
			}
			goto('/profiles');
		} catch (e) {
			const msg = e instanceof Error ? e.message : String(e);
			notifications.add(`Failed to save profile: ${msg}`, 'error');
		} finally {
			saving = false;
		}
	}
</script>

<svelte:window onkeydown={handleKeydown} />

<div class="space-y-4">
	<div class="flex items-center justify-between">
		<h1 class="text-2xl font-bold text-foreground">
			{profileId ? 'Edit Profile' : 'New Profile'}
		</h1>
		<div class="flex gap-2">
			<button
				onclick={() => goto('/profiles')}
				class="rounded-md border border-border px-4 py-2 text-sm font-medium text-foreground hover:bg-accent"
			>
				Cancel
			</button>
			<button
				onclick={handleSave}
				disabled={saving || !name.trim()}
				class="rounded-md bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 disabled:opacity-50"
			>
				{saving ? 'Saving...' : 'Save'}
			</button>
		</div>
	</div>

	<!-- Metadata -->
	<div class="rounded-lg border border-border bg-card p-4">
		<h2 class="mb-3 text-sm font-semibold text-foreground">Profile Details</h2>
		<div class="grid gap-3 sm:grid-cols-2">
			<div class="sm:col-span-2">
				<label for="profile-name" class="mb-1 block text-xs font-medium text-muted-foreground">Name *</label>
				<input
					id="profile-name"
					type="text"
					bind:value={name}
					placeholder="My Roast Profile"
					class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground"
				/>
			</div>
			<div class="sm:col-span-2">
				<label for="profile-description" class="mb-1 block text-xs font-medium text-muted-foreground">Description</label>
				<input
					id="profile-description"
					type="text"
					bind:value={description}
					placeholder="Optional description"
					class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground"
				/>
			</div>
			<div>
				<label for="charge-temp" class="mb-1 block text-xs font-medium text-muted-foreground">Charge Temp (°C)</label>
				<input
					id="charge-temp"
					type="number"
					bind:value={chargeTemp}
					placeholder="200"
					class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground"
				/>
			</div>
			<div>
				<label for="target-end-temp" class="mb-1 block text-xs font-medium text-muted-foreground">Target End Temp (°C)</label>
				<input
					id="target-end-temp"
					type="number"
					bind:value={targetEndTemp}
					placeholder="215"
					class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground"
				/>
			</div>
		</div>
	</div>

	<!-- Chart / Table toggle -->
	<div class="rounded-lg border border-border bg-card p-4">
		<div class="mb-3 flex items-center justify-between">
			<h2 class="text-sm font-semibold text-foreground">
				Profile Points ({points.length})
			</h2>
			<div class="flex gap-1">
				<button
					onclick={() => (viewMode = 'chart')}
					class="rounded px-2 py-1 text-xs {viewMode === 'chart' ? 'bg-amber-500/20 text-amber-400' : 'text-muted-foreground hover:text-foreground'}"
					title="Chart view"
				>
					<LineChart class="h-4 w-4" />
				</button>
				<button
					onclick={() => (viewMode = 'table')}
					class="rounded px-2 py-1 text-xs {viewMode === 'table' ? 'bg-amber-500/20 text-amber-400' : 'text-muted-foreground hover:text-foreground'}"
					title="Table view"
				>
					<Table class="h-4 w-4" />
				</button>
				{#if selectedIndex !== null}
					<button
						onclick={deleteSelected}
						class="ml-2 rounded px-2 py-1 text-xs text-red-400 hover:bg-red-500/10 hover:text-red-300"
						title="Delete selected point"
					>
						<Trash2 class="h-4 w-4" />
					</button>
				{/if}
			</div>
		</div>

		{#if viewMode === 'chart'}
			<p class="mb-2 text-xs text-muted-foreground">Click on the chart to add points. Click a point to select it.</p>
			<div style="height: 350px;">
				<Chart bind:this={chartComponent} option={chartOption} />
			</div>
		{:else}
			<!-- Table view -->
			{#if points.length === 0}
				<p class="py-4 text-center text-sm text-muted-foreground">No points yet. Switch to chart view and click to add points.</p>
			{:else}
				<div class="overflow-x-auto">
					<table class="w-full text-sm">
						<thead>
							<tr class="border-b border-border text-left text-xs text-muted-foreground">
								<th class="px-3 py-2">Time (s)</th>
								<th class="px-3 py-2">Temp (°C)</th>
								<th class="px-3 py-2">Fan Speed</th>
								<th class="px-3 py-2 w-10"></th>
							</tr>
						</thead>
						<tbody>
							{#each sortedPoints() as point, i}
								{@const realIndex = points.indexOf(point)}
								<tr
									class="border-b border-border/50 {selectedIndex === realIndex ? 'bg-amber-500/10' : 'hover:bg-accent'}"
									onclick={() => (selectedIndex = realIndex)}
								>
									<td class="px-3 py-1.5">
										<input
											type="number"
											value={point.time_seconds}
											oninput={(e) => {
												const val = parseInt((e.target as HTMLInputElement).value);
												if (!isNaN(val) && val >= 0) points[realIndex].time_seconds = val;
											}}
											class="w-20 rounded border border-border bg-input px-2 py-1 text-sm text-foreground"
											min="0"
										/>
									</td>
									<td class="px-3 py-1.5">
										<input
											type="number"
											value={point.target_temp}
											oninput={(e) => {
												const val = parseFloat((e.target as HTMLInputElement).value);
												if (!isNaN(val) && val >= 0) points[realIndex].target_temp = val;
											}}
											class="w-20 rounded border border-border bg-input px-2 py-1 text-sm text-foreground"
											step="0.1"
											min="0"
										/>
									</td>
									<td class="px-3 py-1.5">
										<input
											type="number"
											value={point.fan_speed ?? ''}
											oninput={(e) => {
												const v = (e.target as HTMLInputElement).value;
												points[realIndex].fan_speed = v === '' ? null : parseInt(v);
											}}
											class="w-20 rounded border border-border bg-input px-2 py-1 text-sm text-foreground"
											placeholder="-"
											min="0"
											max="255"
										/>
									</td>
									<td class="px-3 py-1.5">
										<button
											onclick={(e) => { e.stopPropagation(); selectedIndex = realIndex; deleteSelected(); }}
											class="text-red-400 hover:text-red-300"
											title="Delete point"
										>
											<Trash2 class="h-3.5 w-3.5" />
										</button>
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			{/if}
		{/if}
	</div>

	<!-- Selected point editor (chart view) -->
	{#if viewMode === 'chart' && selectedIndex !== null && selectedIndex >= 0 && selectedIndex < points.length}
		{@const point = points[selectedIndex]}
		<div class="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4">
			<h3 class="mb-2 text-sm font-semibold text-amber-400">Selected Point</h3>
			<div class="grid gap-3 sm:grid-cols-3">
				<div>
					<label for="edit-time" class="mb-1 block text-xs font-medium text-muted-foreground">Time (seconds)</label>
					<input
						id="edit-time"
						type="number"
						bind:value={point.time_seconds}
						class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground"
						min="0"
					/>
				</div>
				<div>
					<label for="edit-temp" class="mb-1 block text-xs font-medium text-muted-foreground">Temperature (°C)</label>
					<input
						id="edit-temp"
						type="number"
						bind:value={point.target_temp}
						class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground"
						step="0.1"
						min="0"
					/>
				</div>
				<div>
					<label for="edit-fan" class="mb-1 block text-xs font-medium text-muted-foreground">Fan Speed (0-255)</label>
					<input
						id="edit-fan"
						type="number"
						value={point.fan_speed ?? ''}
						oninput={(e) => {
							const v = (e.target as HTMLInputElement).value;
							point.fan_speed = v === '' ? null : parseInt(v);
						}}
						class="w-full rounded border border-border bg-input px-3 py-1.5 text-sm text-foreground"
						placeholder="Optional"
						min="0"
						max="255"
					/>
				</div>
			</div>
		</div>
	{/if}
</div>

// apps/dashboard/src/components/ProfileDesigner.tsx
import { useState, useMemo, useCallback } from 'react'
import ReactECharts from 'echarts-for-react'
import { CreateProfileRequest, CreateProfilePointRequest } from '../api/client'
import { 
  calculateRoR, 
  profilePointsToTemperaturePoints, 
  DEFAULT_ROR_CONFIG,
  calculateRoastPhaseStats,
  type TemperaturePoint 
} from '../utils/rorCalculations'

type Props = {
  onSave: (profile: CreateProfileRequest) => void
  onCancel: () => void
  initialProfile?: CreateProfileRequest
}

export function ProfileDesigner({ onSave, onCancel, initialProfile }: Props) {
  const [profile, setProfile] = useState<CreateProfileRequest>(
    initialProfile || {
      name: '',
      description: '',
      points: [
        { time_seconds: 0, target_temp: 100 },
        { time_seconds: 300, target_temp: 150 },
        { time_seconds: 600, target_temp: 200 },
        { time_seconds: 900, target_temp: 220 }
      ]
    }
  )

  const [selectedPointIndex, setSelectedPointIndex] = useState<number | null>(null)
  const [showRoR, setShowRoR] = useState(true)
  const [dragMode, setDragMode] = useState(false)

  // Calculate RoR data for current profile
  const { rorData, phaseStats } = useMemo(() => {
    if (profile.points.length < 2) {
      return { rorData: [], phaseStats: null }
    }

    const temperaturePoints: TemperaturePoint[] = profile.points
      .sort((a, b) => a.time_seconds - b.time_seconds)
      .map(point => ({
        time: point.time_seconds,
        temperature: point.target_temp
      }))

    const rorPoints = calculateRoR(temperaturePoints, DEFAULT_ROR_CONFIG)
    const stats = calculateRoastPhaseStats(rorPoints)

    return { rorData: rorPoints, phaseStats: stats }
  }, [profile.points])

  // Chart click handler for adding/editing points
  const handleChartClick = useCallback((params: any) => {
    if (!params || params.componentType !== 'grid') return

    const [timeSeconds, temperature] = params.value || [params.dataIndex * 60, 150]
    
    if (dragMode) {
      // Add new point at clicked location
      const newPoint: CreateProfilePointRequest = {
        time_seconds: Math.round(timeSeconds),
        target_temp: Math.round(temperature)
      }

      setProfile(prev => ({
        ...prev,
        points: [...prev.points, newPoint].sort((a, b) => a.time_seconds - b.time_seconds)
      }))
    }
  }, [dragMode])

  // Update point values
  const updatePoint = (index: number, field: keyof CreateProfilePointRequest, value: number) => {
    setProfile(prev => ({
      ...prev,
      points: prev.points.map((point, i) => 
        i === index ? { ...point, [field]: value } : point
      )
    }))
  }

  // Remove point
  const removePoint = (index: number) => {
    if (profile.points.length <= 2) {
      alert('Profile must have at least 2 points')
      return
    }
    
    setProfile(prev => ({
      ...prev,
      points: prev.points.filter((_, i) => i !== index)
    }))
  }

  // Add point at specific time
  const addPointAtTime = (timeSeconds: number) => {
    // Find appropriate temperature by interpolating between existing points
    const sortedPoints = [...profile.points].sort((a, b) => a.time_seconds - b.time_seconds)
    let targetTemp = 150

    for (let i = 0; i < sortedPoints.length - 1; i++) {
      const p1 = sortedPoints[i]
      const p2 = sortedPoints[i + 1]
      
      if (timeSeconds >= p1.time_seconds && timeSeconds <= p2.time_seconds) {
        const ratio = (timeSeconds - p1.time_seconds) / (p2.time_seconds - p1.time_seconds)
        targetTemp = p1.target_temp + ratio * (p2.target_temp - p1.target_temp)
        break
      }
    }

    const newPoint: CreateProfilePointRequest = {
      time_seconds: timeSeconds,
      target_temp: Math.round(targetTemp)
    }

    setProfile(prev => ({
      ...prev,
      points: [...prev.points, newPoint].sort((a, b) => a.time_seconds - b.time_seconds)
    }))
  }

  // Generate roast phase templates
  const applyTemplate = (templateType: 'light' | 'medium' | 'dark') => {
    const templates = {
      light: [
        { time_seconds: 0, target_temp: 100 },
        { time_seconds: 120, target_temp: 140 },
        { time_seconds: 300, target_temp: 170 },
        { time_seconds: 480, target_temp: 195 },
        { time_seconds: 600, target_temp: 205 },
        { time_seconds: 720, target_temp: 210 }
      ],
      medium: [
        { time_seconds: 0, target_temp: 100 },
        { time_seconds: 150, target_temp: 145 },
        { time_seconds: 360, target_temp: 175 },
        { time_seconds: 540, target_temp: 200 },
        { time_seconds: 720, target_temp: 215 },
        { time_seconds: 840, target_temp: 220 }
      ],
      dark: [
        { time_seconds: 0, target_temp: 100 },
        { time_seconds: 180, target_temp: 150 },
        { time_seconds: 420, target_temp: 180 },
        { time_seconds: 600, target_temp: 205 },
        { time_seconds: 780, target_temp: 220 },
        { time_seconds: 900, target_temp: 230 }
      ]
    }

    setProfile(prev => ({
      ...prev,
      points: templates[templateType]
    }))
  }

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  // Export profile to JSON file
  const exportToJSON = () => {
    const exportData = {
      name: profile.name,
      description: profile.description,
      points: profile.points.sort((a, b) => a.time_seconds - b.time_seconds)
    }
    
    const dataStr = JSON.stringify(exportData, null, 2)
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr)
    
    const exportFileDefaultName = `${profile.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_profile.json`
    
    const linkElement = document.createElement('a')
    linkElement.setAttribute('href', dataUri)
    linkElement.setAttribute('download', exportFileDefaultName)
    linkElement.click()
  }

  // Export profile to CSV file
  const exportToCSV = () => {
    const csvHeader = 'time_seconds,target_temp,fan_speed\n'
    const csvData = profile.points
      .sort((a, b) => a.time_seconds - b.time_seconds)
      .map(point => `${point.time_seconds},${point.target_temp},${point.fan_speed || ''}`)
      .join('\n')
    
    const csvContent = csvHeader + csvData
    const dataUri = 'data:text/csv;charset=utf-8,' + encodeURIComponent(csvContent)
    
    const exportFileDefaultName = `${profile.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_profile.csv`
    
    const linkElement = document.createElement('a')
    linkElement.setAttribute('href', dataUri)
    linkElement.setAttribute('download', exportFileDefaultName)
    linkElement.click()
  }

  const maxTime = Math.max(...profile.points.map(p => p.time_seconds), 1200)
  const maxTemp = Math.max(...profile.points.map(p => p.target_temp), 250)

  const chartOptions = {
    title: {
      text: profile.name || 'Profile Designer',
      left: 'center',
      textStyle: { fontSize: 16, fontWeight: 'bold' }
    },
    tooltip: {
      trigger: 'axis',
      formatter: (params: any) => {
        let tooltip = ''
        for (const param of params) {
          const time = Math.floor(param.value[0] / 60)
          const timeStr = `${time}:${(param.value[0] % 60).toString().padStart(2, '0')}`
          
          if (param.seriesName === 'Temperature Profile') {
            tooltip += `Time: ${timeStr}<br/>Temperature: ${param.value[1].toFixed(1)}°C<br/>`
          } else if (param.seriesName === 'Rate of Rise') {
            tooltip += `RoR: ${param.value[1].toFixed(1)}°C/min<br/>`
          }
        }
        return tooltip
      }
    },
    legend: {
      data: showRoR ? ['Temperature Profile', 'Rate of Rise'] : ['Temperature Profile'],
      top: '40px'
    },
    grid: {
      left: '60px',
      right: '60px',
      bottom: '60px',
      top: '100px'
    },
    xAxis: {
      type: 'value',
      name: 'Time (minutes)',
      nameLocation: 'middle',
      nameGap: 30,
      axisLabel: {
        formatter: (value: number) => {
          const mins = Math.floor(value / 60)
          return `${mins}:${(value % 60).toString().padStart(2, '0')}`
        }
      },
      min: 0,
      max: maxTime
    },
    yAxis: [
      {
        type: 'value',
        name: 'Temperature (°C)',
        nameLocation: 'middle',
        nameGap: 40,
        min: 50,
        max: maxTemp + 20,
        position: 'left'
      },
      ...(showRoR && phaseStats ? [{
        type: 'value',
        name: 'RoR (°C/min)',
        nameLocation: 'middle',
        nameGap: 40,
        min: phaseStats.minRoR - 2,
        max: phaseStats.maxRoR + 2,
        position: 'right'
      }] : [])
    ],
    series: [
      {
        name: 'Temperature Profile',
        type: 'line',
        yAxisIndex: 0,
        data: profile.points
          .sort((a, b) => a.time_seconds - b.time_seconds)
          .map(point => [point.time_seconds, point.target_temp]),
        smooth: true,
        symbol: 'circle',
        symbolSize: 8,
        itemStyle: { color: '#3b82f6' },
        lineStyle: { color: '#3b82f6', width: 3 },
        areaStyle: {
          color: {
            type: 'linear',
            x: 0, y: 0, x2: 0, y2: 1,
            colorStops: [
              { offset: 0, color: 'rgba(59, 130, 246, 0.3)' },
              { offset: 1, color: 'rgba(59, 130, 246, 0.1)' }
            ]
          }
        }
      },
      ...(showRoR && rorData.length > 0 ? [{
        name: 'Rate of Rise',
        type: 'line',
        yAxisIndex: 1,
        data: rorData.map(point => [point.time, point.ror]),
        smooth: true,
        symbol: 'none',
        itemStyle: { color: '#ef4444' },
        lineStyle: { color: '#ef4444', width: 2 }
      }] : [])
    ]
  }

  const isValidProfile = profile.name.trim() && profile.points.length >= 2

  return (
    <div className="p-6 bg-white rounded-lg border border-gray-200">
      <div className="mb-6">
        <h2 className="text-xl font-bold mb-4">Profile Designer</h2>
        
        {/* Profile metadata */}
        <div className="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label className="block text-sm font-medium mb-1">Profile Name *</label>
            <input
              type="text"
              value={profile.name}
              onChange={e => setProfile(prev => ({ ...prev, name: e.target.value }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
              placeholder="Enter profile name"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1">Description</label>
            <input
              type="text"
              value={profile.description}
              onChange={e => setProfile(prev => ({ ...prev, description: e.target.value }))}
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm"
              placeholder="Optional description"
            />
          </div>
        </div>

        {/* Template buttons */}
        <div className="flex gap-2 mb-4">
          <button
            onClick={() => applyTemplate('light')}
            className="px-3 py-1 bg-yellow-500 text-white rounded text-sm hover:bg-yellow-600"
          >
            Light Roast Template
          </button>
          <button
            onClick={() => applyTemplate('medium')}
            className="px-3 py-1 bg-orange-500 text-white rounded text-sm hover:bg-orange-600"
          >
            Medium Roast Template
          </button>
          <button
            onClick={() => applyTemplate('dark')}
            className="px-3 py-1 bg-red-800 text-white rounded text-sm hover:bg-red-900"
          >
            Dark Roast Template
          </button>
        </div>

        {/* Chart controls */}
        <div className="flex justify-between items-center mb-4">
          <div className="flex items-center gap-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={showRoR}
                onChange={e => setShowRoR(e.target.checked)}
              />
              <span className="text-sm">Show Rate of Rise</span>
            </label>
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={dragMode}
                onChange={e => setDragMode(e.target.checked)}
              />
              <span className="text-sm">Click to Add Points</span>
            </label>
          </div>
          
          {phaseStats && showRoR && (
            <div className="text-sm text-gray-600">
              Avg RoR: {phaseStats.overallRoR.toFixed(1)}°C/min | 
              Max: {phaseStats.maxRoR.toFixed(1)}°C/min
            </div>
          )}
        </div>
      </div>

      {/* Chart */}
      <div className="mb-6">
        <ReactECharts 
          option={chartOptions}
          style={{ width: '100%', height: '400px' }}
          opts={{ renderer: 'canvas' }}
          onEvents={{ click: handleChartClick }}
        />
      </div>

      {/* Point editor */}
      <div className="mb-6">
        <div className="flex justify-between items-center mb-3">
          <h3 className="text-lg font-semibold">Profile Points ({profile.points.length})</h3>
          <button
            onClick={() => addPointAtTime(Math.max(...profile.points.map(p => p.time_seconds)) + 120)}
            className="px-3 py-1 bg-green-500 text-white rounded text-sm hover:bg-green-600"
          >
            Add Point
          </button>
        </div>
        
        <div className="max-h-48 overflow-y-auto border border-gray-200 rounded">
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-3 py-2 text-left">Time</th>
                <th className="px-3 py-2 text-left">Time (s)</th>
                <th className="px-3 py-2 text-left">Temperature (°C)</th>
                <th className="px-3 py-2 text-left">Fan Speed</th>
                <th className="px-3 py-2 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {profile.points
                .sort((a, b) => a.time_seconds - b.time_seconds)
                .map((point, index) => (
                  <tr key={index} className={selectedPointIndex === index ? 'bg-blue-50' : ''}>
                    <td className="px-3 py-2 font-mono">{formatTime(point.time_seconds)}</td>
                    <td className="px-3 py-2">
                      <input
                        type="number"
                        value={point.time_seconds}
                        onChange={e => updatePoint(index, 'time_seconds', parseInt(e.target.value) || 0)}
                        className="w-20 px-2 py-1 border border-gray-300 rounded text-xs"
                      />
                    </td>
                    <td className="px-3 py-2">
                      <input
                        type="number"
                        value={point.target_temp}
                        onChange={e => updatePoint(index, 'target_temp', parseFloat(e.target.value) || 0)}
                        className="w-20 px-2 py-1 border border-gray-300 rounded text-xs"
                      />
                    </td>
                    <td className="px-3 py-2">
                      <input
                        type="number"
                        value={point.fan_speed || ''}
                        onChange={e => updatePoint(index, 'fan_speed', parseInt(e.target.value) || undefined)}
                        placeholder="0-255"
                        className="w-20 px-2 py-1 border border-gray-300 rounded text-xs"
                      />
                    </td>
                    <td className="px-3 py-2">
                      <button
                        onClick={() => removePoint(index)}
                        disabled={profile.points.length <= 2}
                        className="px-2 py-1 bg-red-500 text-white rounded text-xs hover:bg-red-600 disabled:bg-gray-300"
                      >
                        Remove
                      </button>
                    </td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3 flex-wrap">
        <button
          onClick={() => onSave(profile)}
          disabled={!isValidProfile}
          className={`px-6 py-2 rounded text-sm font-medium ${
            isValidProfile 
              ? 'bg-blue-500 text-white hover:bg-blue-600' 
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
          }`}
        >
          Save Profile
        </button>
        
        <button
          onClick={exportToJSON}
          disabled={!isValidProfile}
          className={`px-4 py-2 rounded text-sm font-medium ${
            isValidProfile 
              ? 'bg-green-500 text-white hover:bg-green-600' 
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
          }`}
        >
          Export JSON
        </button>
        
        <button
          onClick={exportToCSV}
          disabled={!isValidProfile}
          className={`px-4 py-2 rounded text-sm font-medium ${
            isValidProfile 
              ? 'bg-teal-500 text-white hover:bg-teal-600' 
              : 'bg-gray-300 text-gray-500 cursor-not-allowed'
          }`}
        >
          Export CSV
        </button>
        
        <button
          onClick={onCancel}
          className="px-6 py-2 bg-gray-500 text-white rounded text-sm font-medium hover:bg-gray-600"
        >
          Cancel
        </button>
      </div>
    </div>
  )
}
